<?php

$servername =  "localhost";
$username =  "root";
$password =  "";
$dbname =  "greenhub"; 

$con = new mysqli($servername,$username,$password,$dbname);

if($con -> connect_errno)
{ 
    die("<br>the error message generated by the system is: ". $con->connect_error);   
}

?>